### ISSUE TITLE
System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by a34546** [xljiulang/ServiceSelf#6]
PS E:\Demo\WebApiUseServiceSelf\bin\Release\net6.0\publish> .\WebApiUseServiceSelf.exe start
Unhandled exception. System.ComponentModel.Win32Exception (1053): 服务没有及时响应启动或控制请求。
   at ServiceSelf.WindowsService.StartService(SafeServiceHandle serviceHandle)
   at ServiceSelf.WindowsService.CreateStart(String filePath, ServiceOptions options)
   at ServiceSelf.Service.UseCommand(Command command, IEnumerable`1 arguments, String name, ServiceOptions options)
   at ServiceSelf.Service.UseServiceSelf(String[] args, String serviceName, ServiceOptions serviceOptions)
   at WebApiUseServiceSelf.Program.Main(String[] args) in 
E:\Demo\WebApiUseServiceSelf\Program.cs:line 21

```C#
using ServiceSelf;
using System.ServiceProcess;

namespace WebApiUseServiceSelf
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var serviceName = "WebApiUseServiceSelf";

            var serviceOptions = new ServiceOptions
            {
                Description = "WebApi使用服务托管运行测试",
            };
            serviceOptions.Linux.Service.Restart = "always";
            serviceOptions.Linux.Service.RestartSec = "10";
            serviceOptions.Windows.DisplayName = "WebApi使用服务托管运行";
            serviceOptions.Windows.FailureActionType = WindowsServiceActionType.Restart;

            if (Service.UseServiceSelf(args, serviceName, serviceOptions))
            {
                var builder = WebApplication.CreateBuilder(args);
                builder.Services.AddControllers();
                builder.Services.AddEndpointsApiExplorer();
                builder.Services.AddSwaggerGen();
                var app = builder.Build();
                app.UseSwagger();
                app.UseSwaggerUI();
                app.UseAuthorization();
                app.MapControllers();
                app.Run();

            }
        }
    }
}
```

**Comment by xljiulang** [comment]
少了调用 
```
// 为Host配置UseServiceSelf()
builder.Host.UseServiceSelf();
```
